### ISSUE TITLE
Check behavior when user submitted content is not in the dimensions we expect

### ISSUE THREAD

**Issue by din0s** [din0s/ActionHeroes#29]
When a user submits an image, they might choose a file that's not suitable for our containers. We should double-check to make sure that such images don't break the layout of the site!

(By extension, this could also apply to text/descriptions entered by the user)

**Comment by SotirisFtiakas** [comment]
For the img tags, would the css property “object-fit” be a possible solution?

**Comment by din0s** [comment]
This was addressed with #58.
