### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by din0s** [din0s/ActionHeroes#3]
The navigation bar that is to be introduced with PR #2 may change based on whether a user is logged in or if it's someone viewing the website as a guest.

Should we create a basic/dummy implementation for authentication in the back end right now, or leave that for a later point in time and proceed as is with a guest-only view?

**Comment by chriskrez** [comment]
We can implement a simple authentication, for start, in order to continue with the signed-in version of the navigation bar.

**Comment by din0s** [comment]
Ok, I will refactor the navbar to support both versions then.
